use crate::backend::BackendResult;
use serde::{Deserialize, Serialize};
use std::path::PathBuf;

/// SDF timing corner
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum TimingCorner {
    WC,  // Worst case
    BC,  // Best case
    TYP, // Typical
}

impl std::fmt::Display for TimingCorner {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            TimingCorner::WC => write!(f, "WC"),
            TimingCorner::BC => write!(f, "BC"),
            TimingCorner::TYP => write!(f, "TYP"),
        }
    }
}

/// SDF file format specification
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum SdfFormat {
    #[serde(rename = "sdf_2_1")]
    Sdf21,
    #[serde(rename = "sdf_3_0")]
    Sdf30,
}

impl std::fmt::Display for SdfFormat {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            SdfFormat::Sdf21 => write!(f, "2.1"),
            SdfFormat::Sdf30 => write!(f, "3.0"),
        }
    }
}

/// SDF file header information
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SdfHeader {
    pub format: SdfFormat,
    pub design_name: String,
    pub date: String,
    pub vendor: String,
    pub program: String,
    pub version: String,
    pub divider: char,
    pub time_unit: String,
    pub voltage: Vec<String>,
    pub temperature: Vec<String>,
}

impl Default for SdfHeader {
    fn default() -> Self {
        Self {
            format: SdfFormat::Sdf21,
            design_name: String::new(),
            date: chrono::Local::now().to_rfc3339(),
            vendor: "CovertEDA".to_string(),
            program: "CovertEDA".to_string(),
            version: "1.0".to_string(),
            divider: '/'.to_string(),
            time_unit: "1ns".to_string(),
            voltage: vec!["1.0".to_string()],
            temperature: vec!["25.0".to_string()],
        }
    }
}

/// Backannotation configuration
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BackannotationConfig {
    pub design_name: String,
    pub output_dir: PathBuf,
    pub timing_corner: TimingCorner,
    pub include_delays: bool,
    pub include_interconnect: bool,
    pub scale_factor: f64,
    pub voltage: f64,
    pub temperature: f64,
}

impl Default for BackannotationConfig {
    fn default() -> Self {
        Self {
            design_name: "top".to_string(),
            output_dir: PathBuf::from("."),
            timing_corner: TimingCorner::TYP,
            include_delays: true,
            include_interconnect: true,
            scale_factor: 1.0,
            voltage: 1.0,
            temperature: 25.0,
        }
    }
}

/// Generate SDF backannotation TCL script
pub fn generate_backannotation_tcl(config: &BackannotationConfig) -> BackendResult<String> {
    let output_file = config
        .output_dir
        .join(format!("{}.sdf", config.design_name));

    let tcl = format!(
        r#"# Backannotation Script - Generated by CovertEDA
# Design: {}

# Configure SDF parameters
set sdf_file "{}"
set timing_corner {}
set include_interconnect {}

# Generate SDF file
if {{ [catch {{
    # Radiant-specific SDF generation
    open_project [get_project_name]

    # Set timing corner
    configure_tool -name {{SYNTHESIZE}} -params {{SYNPLIFY_OPTIONS:set_option -define TIMING_CORNER={} }}

    # Export SDF
    if {{ $include_interconnect == 1 }} {{
        export_sdf -file $sdf_file -full -interconnect
    }} else {{
        export_sdf -file $sdf_file -full
    }}

    puts "SDF backannotation generated: $sdf_file"
}} error_msg] }} {{
    puts "ERROR: Failed to generate SDF: $error_msg"
    exit 1
}}
"#,
        config.design_name,
        output_file.display(),
        config.timing_corner,
        config.include_interconnect as i32,
        config.timing_corner
    );

    Ok(tcl)
}

/// Find SDF files in a directory
pub fn find_sdf_files(dir: &std::path::Path) -> BackendResult<Vec<PathBuf>> {
    let mut sdf_files = vec![];

    if dir.exists() {
        for entry in std::fs::read_dir(dir)? {
            let entry = entry?;
            let path = entry.path();
            if path
                .extension()
                .and_then(|ext| ext.to_str())
                .map(|s| s.eq_ignore_ascii_case("sdf"))
                .unwrap_or(false)
            {
                sdf_files.push(path);
            }
        }
    }

    Ok(sdf_files)
}

/// Parse SDF header from file
pub fn parse_sdf_header(content: &str) -> BackendResult<SdfHeader> {
    let mut header = SdfHeader::default();

    // Parse SDF version
    if content.contains("(sdf_version \"3.0\"") {
        header.format = SdfFormat::Sdf30;
    } else {
        header.format = SdfFormat::Sdf21;
    }

    // Parse design name
    if let Some(pos) = content.find("(design \"") {
        let rest = &content[pos + 9..];
        if let Some(end) = rest.find('"') {
            header.design_name = rest[..end].to_string();
        }
    }

    // Parse date
    if let Some(pos) = content.find("(date \"") {
        let rest = &content[pos + 7..];
        if let Some(end) = rest.find('"') {
            header.date = rest[..end].to_string();
        }
    }

    // Parse vendor
    if let Some(pos) = content.find("(vendor \"") {
        let rest = &content[pos + 9..];
        if let Some(end) = rest.find('"') {
            header.vendor = rest[..end].to_string();
        }
    }

    // Parse program
    if let Some(pos) = content.find("(program \"") {
        let rest = &content[pos + 10..];
        if let Some(end) = rest.find('"') {
            header.program = rest[..end].to_string();
        }
    }

    // Parse time unit
    if let Some(pos) = content.find("(timeunit \"") {
        let rest = &content[pos + 11..];
        if let Some(end) = rest.find('"') {
            header.time_unit = rest[..end].to_string();
        }
    }

    Ok(header)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_backannotation_config_default() {
        let config = BackannotationConfig::default();
        assert_eq!(config.design_name, "top");
        assert_eq!(config.scale_factor, 1.0);
        assert_eq!(config.voltage, 1.0);
        assert_eq!(config.temperature, 25.0);
    }

    #[test]
    fn test_generate_backannotation_tcl() {
        let config = BackannotationConfig::default();
        let tcl = generate_backannotation_tcl(&config).unwrap();
        assert!(tcl.contains("export_sdf"));
        assert!(tcl.contains("top"));
        assert!(tcl.contains("Backannotation Script"));
    }

    #[test]
    fn test_parse_sdf_header() {
        let content = r#"
(sdf_version "3.0")
(design "my_design")
(date "2024-01-01T00:00:00")
(vendor "CovertEDA")
(program "Radiant")
(timeunit "1ns")
"#;
        let header = parse_sdf_header(content).unwrap();
        assert_eq!(header.design_name, "my_design");
        assert_eq!(header.vendor, "CovertEDA");
    }

    #[test]
    fn test_timing_corner_display() {
        assert_eq!(TimingCorner::WC.to_string(), "WC");
        assert_eq!(TimingCorner::BC.to_string(), "BC");
        assert_eq!(TimingCorner::TYP.to_string(), "TYP");
    }

    #[test]
    fn test_sdf_format_display() {
        assert_eq!(SdfFormat::Sdf21.to_string(), "2.1");
        assert_eq!(SdfFormat::Sdf30.to_string(), "3.0");
    }
}
