use crate::backend::BackendResult;
use serde::{Deserialize, Serialize};
use std::path::PathBuf;

/// Bitstream encryption mode
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum EncryptionMode {
    None,
    AES128,
    AES256,
    Proprietary,
}

impl std::fmt::Display for EncryptionMode {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            EncryptionMode::None => write!(f, "none"),
            EncryptionMode::AES128 => write!(f, "aes128"),
            EncryptionMode::AES256 => write!(f, "aes256"),
            EncryptionMode::Proprietary => write!(f, "proprietary"),
        }
    }
}

/// Configuration port for security key injection
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ConfigPort {
    pub port_name: String,
    pub key_width: u32,
    pub key_format: String,
    pub allow_jtag: bool,
    pub allow_serial: bool,
}

impl Default for ConfigPort {
    fn default() -> Self {
        Self {
            port_name: "config_port".to_string(),
            key_width: 256,
            key_format: "binary".to_string(),
            allow_jtag: true,
            allow_serial: false,
        }
    }
}

/// Bitstream security configuration
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BitstreamSecurityConfig {
    pub design_name: String,
    pub encryption_mode: EncryptionMode,
    pub encryption_key: String,
    pub enable_authentication: bool,
    pub enable_bitstream_crc: bool,
    pub config_port: Option<ConfigPort>,
    pub restrict_readback: bool,
    pub disable_jtag_readback: bool,
}

impl Default for BitstreamSecurityConfig {
    fn default() -> Self {
        Self {
            design_name: "top".to_string(),
            encryption_mode: EncryptionMode::AES256,
            encryption_key: String::new(),
            enable_authentication: true,
            enable_bitstream_crc: true,
            config_port: Some(ConfigPort::default()),
            restrict_readback: true,
            disable_jtag_readback: false,
        }
    }
}

/// Generate security options TCL snippet
pub fn generate_security_options(config: &BitstreamSecurityConfig) -> BackendResult<String> {
    let mut options = String::from(
        r#"# Bitstream Security Options - Generated by CovertEDA

set security_enabled 1
set encryption_mode "#,
    );
    options.push_str(&config.encryption_mode.to_string());
    options.push_str(
        r#"
set enable_crc "#,
    );
    options.push_str(&(config.enable_bitstream_crc as i32).to_string());
    options.push_str(
        r#"
set enable_authentication "#,
    );
    options.push_str(&(config.enable_authentication as i32).to_string());
    options.push_str(
        r#"
set restrict_readback "#,
    );
    options.push_str(&(config.restrict_readback as i32).to_string());
    options.push_str(
        r#"
set disable_jtag_readback "#,
    );
    options.push_str(&(config.disable_jtag_readback as i32).to_string());
    options.push_str("\n");

    if let Some(ref port) = config.config_port {
        options.push_str(&format!(
            r#"
# Configuration Port
set config_port_name "{}"
set config_key_width {}
set allow_jtag_access {}
set allow_serial_access {}
"#,
            port.port_name,
            port.key_width,
            port.allow_jtag as i32,
            port.allow_serial as i32
        ));
    }

    Ok(options)
}

/// Generate Radiant security TCL script
pub fn generate_security_tcl(config: &BitstreamSecurityConfig) -> BackendResult<String> {
    let mut tcl = String::from(
        r#"# Bitstream Security Configuration - Generated by CovertEDA
# Design: "#,
    );
    tcl.push_str(&config.design_name);
    tcl.push_str(
        r#"

open_project [get_project_name]

# Configure bitstream security
configure_tool -name {{BITGEN}} -params {{
    BITGEN_OPTIONS:set_option -configure -encrypt_key 1 "#,
    );
    tcl.push_str(&config.encryption_key);
    tcl.push_str(
        r#"
    BITGEN_OPTIONS:set_option -encryption_mode "#,
    );
    tcl.push_str(&config.encryption_mode.to_string());
    tcl.push_str(
        r#"
"#,
    );

    if config.enable_bitstream_crc {
        tcl.push_str("    BITGEN_OPTIONS:set_option -generate_crc\n");
    }

    if config.enable_authentication {
        tcl.push_str("    BITGEN_OPTIONS:set_option -enable_authentication\n");
    }

    if config.restrict_readback {
        tcl.push_str("    BITGEN_OPTIONS:set_option -restrict_bitstream_readback\n");
    }

    if config.disable_jtag_readback {
        tcl.push_str("    BITGEN_OPTIONS:set_option -disable_jtag_readback\n");
    }

    tcl.push_str("}\n\n");

    if let Some(ref port) = config.config_port {
        tcl.push_str(&format!(
            r#"# Configure security port
add_io_port -name {{{}}} -direction {{in}} -width {} -io_standard LVCMOS33

# Map configuration key path
set_property CONFIG_PORT:KEY_FILE [get_ports {{{}}}] /path/to/key.bin

"#,
            port.port_name, port.key_width, port.port_name
        ));
    }

    tcl.push_str(
        r#"# Run bitstream generation with security
if { [catch {
    run_tool -name BITGEN
} error_msg] } {
    puts "ERROR: Bitstream generation failed: $error_msg"
    exit 1
}

# Verify bitstream security
if { [file exists "design.bit"] } {
    puts "Secure bitstream generated: design.bit"
    # Verify CRC if enabled
"#,
    );

    if config.enable_bitstream_crc {
        tcl.push_str("    verify_bitstream_crc design.bit\n");
    }

    tcl.push_str("} else {\n    puts \"ERROR: Bitstream generation failed\"\n    exit 1\n}\n");

    Ok(tcl)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_bitstream_security_config_default() {
        let config = BitstreamSecurityConfig::default();
        assert_eq!(config.design_name, "top");
        assert!(config.enable_authentication);
        assert!(config.restrict_readback);
    }

    #[test]
    fn test_encryption_mode_display() {
        assert_eq!(EncryptionMode::None.to_string(), "none");
        assert_eq!(EncryptionMode::AES128.to_string(), "aes128");
        assert_eq!(EncryptionMode::AES256.to_string(), "aes256");
    }

    #[test]
    fn test_generate_security_options() {
        let config = BitstreamSecurityConfig::default();
        let options = generate_security_options(&config).unwrap();
        assert!(options.contains("security_enabled"));
        assert!(options.contains("aes256"));
        assert!(options.contains("enable_crc"));
    }

    #[test]
    fn test_generate_security_tcl() {
        let config = BitstreamSecurityConfig::default();
        let tcl = generate_security_tcl(&config).unwrap();
        assert!(tcl.contains("Bitstream Security"));
        assert!(tcl.contains("BITGEN"));
        assert!(tcl.contains("encryption"));
    }

    #[test]
    fn test_config_port_default() {
        let port = ConfigPort::default();
        assert_eq!(port.port_name, "config_port");
        assert_eq!(port.key_width, 256);
        assert!(port.allow_jtag);
        assert!(!port.allow_serial);
    }

    #[test]
    fn test_security_options_with_port() {
        let mut config = BitstreamSecurityConfig::default();
        config.config_port = Some(ConfigPort {
            port_name: "security_key_in".to_string(),
            key_width: 128,
            key_format: "binary".to_string(),
            allow_jtag: false,
            allow_serial: true,
        });

        let options = generate_security_options(&config).unwrap();
        assert!(options.contains("security_key_in"));
        assert!(options.contains("128"));
    }
}
