use crate::backend::BackendResult;
use serde::{Deserialize, Serialize};

/// I/O port for ECO changes
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EcoIoPort {
    pub port_name: String,
    pub direction: String,
    pub width: u32,
    pub io_standard: String,
}

/// PLL instance for ECO
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EcoPllInstance {
    pub instance_name: String,
    pub pll_type: String,
    pub input_freq_mhz: f64,
    pub output_freq_mhz: f64,
    pub multiplier: u32,
    pub divider: u32,
}

/// Memory instance for ECO
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EcoMemoryInstance {
    pub instance_name: String,
    pub mem_type: String,
    pub width: u32,
    pub depth: u32,
    pub init_file: Option<String>,
}

/// ECO change target
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EcoTargets {
    pub add_ports: Vec<EcoIoPort>,
    pub remove_ports: Vec<String>,
    pub modify_ports: Vec<EcoIoPort>,
    pub add_plls: Vec<EcoPllInstance>,
    pub add_memories: Vec<EcoMemoryInstance>,
    pub add_logic: Vec<String>,
    pub remove_instances: Vec<String>,
}

impl Default for EcoTargets {
    fn default() -> Self {
        Self {
            add_ports: vec![],
            remove_ports: vec![],
            modify_ports: vec![],
            add_plls: vec![],
            add_memories: vec![],
            add_logic: vec![],
            remove_instances: vec![],
        }
    }
}

/// Single ECO change
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EcoChange {
    pub change_id: String,
    pub description: String,
    pub change_type: String,
    pub target: String,
    pub old_value: Option<String>,
    pub new_value: Option<String>,
    pub timestamp: u64,
    pub author: String,
}

/// ECO editing session
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EcoSession {
    pub session_id: String,
    pub design_name: String,
    pub changes: Vec<EcoChange>,
    pub targets: EcoTargets,
    pub locked_for_routing: bool,
}

impl Default for EcoSession {
    fn default() -> Self {
        Self {
            session_id: format!("eco_{}", std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap_or_default()
                .as_nanos()),
            design_name: "top".to_string(),
            changes: vec![],
            targets: EcoTargets::default(),
            locked_for_routing: false,
        }
    }
}

/// Generate ECO TCL script
pub fn generate_eco_tcl(session: &EcoSession) -> BackendResult<String> {
    let mut tcl = String::from(
        r#"# Engineering Change Order (ECO) Script - Generated by CovertEDA
# Session: "#,
    );
    tcl.push_str(&session.session_id);
    tcl.push_str("\n# Design: ");
    tcl.push_str(&session.design_name);
    tcl.push_str(
        r#"

# Open project and context
open_project [get_project_name]
open_eco_session -name "{}"

"#,
    );

    // Add ports
    for port in &session.targets.add_ports {
        tcl.push_str(&format!(
            "add_io_port -name {{{}}} -direction {{{}}} -width {} -io_standard {}\n",
            port.port_name, port.direction, port.width, port.io_standard
        ));
    }

    // Remove ports
    for port_name in &session.targets.remove_ports {
        tcl.push_str(&format!("remove_io_port -name {}\n", port_name));
    }

    // Add PLLs
    for pll in &session.targets.add_plls {
        tcl.push_str(&format!(
            "add_pll_instance -name {{{}}} -type {{{}}} -input_freq {} -output_freq {}\n",
            pll.instance_name, pll.pll_type, pll.input_freq_mhz, pll.output_freq_mhz
        ));
    }

    // Add memories
    for mem in &session.targets.add_memories {
        let init_str = mem
            .init_file
            .as_ref()
            .map(|f| f.as_str())
            .unwrap_or("none");
        tcl.push_str(&format!(
            "add_memory_instance -name {{{}}} -type {{{}}} -width {} -depth {} -init_file {}\n",
            mem.instance_name, mem.mem_type, mem.width, mem.depth, init_str
        ));
    }

    // Close ECO session
    tcl.push_str(
        r#"

# Save and close ECO session
save_eco_session
close_eco_session

puts "ECO script completed successfully"
"#,
    );

    Ok(tcl)
}

/// Scan design for ECO targets
pub fn scan_eco_targets(design_file: &std::path::Path) -> BackendResult<EcoTargets> {
    let mut targets = EcoTargets::default();

    if !design_file.exists() {
        return Ok(targets);
    }

    let content = std::fs::read_to_string(design_file)?;

    // Parse Verilog/VHDL for ports
    for line in content.lines() {
        let trimmed = line.trim();
        if trimmed.starts_with("input") || trimmed.starts_with("output") {
            // Extract port info - simplified parsing
            if let Some(pos) = trimmed.find('[') {
                let rest = &trimmed[pos + 1..];
                if let Some(end) = rest.find(']') {
                    if let Ok(width) = rest[..end].split(':').next().unwrap_or("0").parse::<u32>() {
                        targets.add_ports.push(EcoIoPort {
                            port_name: format!("port_{}", targets.add_ports.len()),
                            direction: if trimmed.starts_with("input") {
                                "in".to_string()
                            } else {
                                "out".to_string()
                            },
                            width: width + 1,
                            io_standard: "LVCMOS33".to_string(),
                        });
                    }
                }
            }
        }
    }

    Ok(targets)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_eco_targets_default() {
        let targets = EcoTargets::default();
        assert!(targets.add_ports.is_empty());
        assert!(targets.remove_ports.is_empty());
    }

    #[test]
    fn test_eco_session_default() {
        let session = EcoSession::default();
        assert_eq!(session.design_name, "top");
        assert!(!session.locked_for_routing);
        assert!(session.changes.is_empty());
    }

    #[test]
    fn test_eco_io_port() {
        let port = EcoIoPort {
            port_name: "test_port".to_string(),
            direction: "in".to_string(),
            width: 8,
            io_standard: "LVCMOS33".to_string(),
        };
        assert_eq!(port.port_name, "test_port");
        assert_eq!(port.width, 8);
    }

    #[test]
    fn test_generate_eco_tcl() {
        let mut session = EcoSession::default();
        session.targets.add_ports.push(EcoIoPort {
            port_name: "new_clk".to_string(),
            direction: "in".to_string(),
            width: 1,
            io_standard: "LVCMOS33".to_string(),
        });

        let tcl = generate_eco_tcl(&session).unwrap();
        assert!(tcl.contains("ECO"));
        assert!(tcl.contains("new_clk"));
        assert!(tcl.contains("add_io_port"));
    }

    #[test]
    fn test_eco_change_creation() {
        let change = EcoChange {
            change_id: "eco_001".to_string(),
            description: "Add clock port".to_string(),
            change_type: "add_port".to_string(),
            target: "clk".to_string(),
            old_value: None,
            new_value: Some("LVCMOS33".to_string()),
            timestamp: 0,
            author: "user".to_string(),
        };

        assert_eq!(change.change_id, "eco_001");
        assert_eq!(change.change_type, "add_port");
    }
}
