use crate::backend::BackendResult;
use serde::{Deserialize, Serialize};
use std::path::PathBuf;

/// Encryption standard/format
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum EncryptionStandard {
    #[serde(rename = "ieee_p1735")]
    IeeeP1735,
    #[serde(rename = "proprietary")]
    Proprietary,
    #[serde(rename = "lattice")]
    Lattice,
    #[serde(rename = "xilinx")]
    Xilinx,
}

impl std::fmt::Display for EncryptionStandard {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            EncryptionStandard::IeeeP1735 => write!(f, "ieee_p1735"),
            EncryptionStandard::Proprietary => write!(f, "proprietary"),
            EncryptionStandard::Lattice => write!(f, "lattice"),
            EncryptionStandard::Xilinx => write!(f, "xilinx"),
        }
    }
}

/// Protected code region
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ProtectRegion {
    pub name: String,
    pub start_line: u32,
    pub end_line: u32,
    pub encryption_key: String,
    pub allow_synthesis: bool,
    pub allow_simulation: bool,
    pub allow_encryption: bool,
}

/// Encryption configuration
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EncryptionConfig {
    pub design_name: String,
    pub standard: EncryptionStandard,
    pub encryption_key: String,
    pub regions: Vec<ProtectRegion>,
    pub output_dir: PathBuf,
    pub create_wrapper: bool,
}

impl Default for EncryptionConfig {
    fn default() -> Self {
        Self {
            design_name: "top".to_string(),
            standard: EncryptionStandard::IeeeP1735,
            encryption_key: String::new(),
            regions: vec![],
            output_dir: PathBuf::from("."),
            create_wrapper: true,
        }
    }
}

/// Encrypted file information
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EncryptedFile {
    pub original_path: PathBuf,
    pub encrypted_path: PathBuf,
    pub wrapper_path: Option<PathBuf>,
    pub standard: EncryptionStandard,
    pub key_checksum: String,
}

/// Generate encryption wrapper HDL
pub fn generate_encryption_wrapper(config: &EncryptionConfig) -> BackendResult<String> {
    let mut wrapper = String::from(
        r#"// IEEE P1735 Encryption Wrapper - Generated by CovertEDA
// Design: "#,
    );
    wrapper.push_str(&config.design_name);
    wrapper.push_str(
        r#"
// This wrapper instantiates the encrypted core

module "#,
    );
    wrapper.push_str(&config.design_name);
    wrapper.push_str(
        r#"_wrapper (
    input wire clk,
    input wire rst_n,
    // Add your ports here
    input wire [31:0] data_in,
    output wire [31:0] data_out
);

    // Instantiate encrypted core
    // pragma protect begin
    // pragma protect encrypt_off

    "#,
    );
    wrapper.push_str(&config.design_name);
    wrapper.push_str(
        r#" core_inst (
        .clk(clk),
        .rst_n(rst_n),
        .data_in(data_in),
        .data_out(data_out)
    );

    // pragma protect encrypt_on
    // pragma protect end

endmodule
"#,
    );

    Ok(wrapper)
}

/// Generate Radiant encryption TCL script
pub fn generate_radiant_encrypt_tcl(config: &EncryptionConfig) -> BackendResult<String> {
    let mut tcl = String::from(
        r#"# Radiant HDL Encryption Script - Generated by CovertEDA
# Design: "#,
    );
    tcl.push_str(&config.design_name);
    tcl.push_str(
        r#"
# Standard: "#,
    );
    tcl.push_str(&config.standard.to_string());
    tcl.push_str(
        r#"

open_project [get_project_name]

# Configure encryption
configure_tool -name {{SYNTHESIZE}} -params {{
    SYNPLIFY_OPTIONS:set_option -define ENCRYPT_ENABLED
    SYNPLIFY_OPTIONS:set_option -define ENCRYPTION_KEY="#,
    );
    tcl.push_str(&config.encryption_key);
    tcl.push_str(
        r#"
}}

"#,
    );

    // Add region protection pragmas
    for region in &config.regions {
        tcl.push_str(&format!(
            r#"# Protect region: {}
add_protect_region -name {{{}}} -start_line {} -end_line {} \
    -allow_synthesis {} -allow_simulation {} -allow_encryption {}
"#,
            region.name,
            region.name,
            region.start_line,
            region.end_line,
            region.allow_synthesis as i32,
            region.allow_simulation as i32,
            region.allow_encryption as i32
        ));
    }

    tcl.push_str(
        r#"

# Export encrypted HDL
if { [catch {
    export_encrypted_hdl -standard "#,
    );
    tcl.push_str(&config.standard.to_string());
    tcl.push_str(
        r#" -output_dir "#,
    );
    tcl.push_str(&config.output_dir.display().to_string());
    tcl.push_str(
        r#"
} error_msg] } {
    puts "ERROR: HDL encryption failed: $error_msg"
    exit 1
}

puts "HDL encryption completed successfully"
"#,
    );

    Ok(tcl)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_encryption_config_default() {
        let config = EncryptionConfig::default();
        assert_eq!(config.design_name, "top");
        assert!(config.create_wrapper);
        assert!(config.regions.is_empty());
    }

    #[test]
    fn test_encryption_standard_display() {
        assert_eq!(EncryptionStandard::IeeeP1735.to_string(), "ieee_p1735");
        assert_eq!(EncryptionStandard::Lattice.to_string(), "lattice");
        assert_eq!(EncryptionStandard::Xilinx.to_string(), "xilinx");
    }

    #[test]
    fn test_generate_encryption_wrapper() {
        let config = EncryptionConfig::default();
        let wrapper = generate_encryption_wrapper(&config).unwrap();
        assert!(wrapper.contains("pragma protect"));
        assert!(wrapper.contains("top_wrapper"));
        assert!(wrapper.contains("module"));
    }

    #[test]
    fn test_generate_radiant_encrypt_tcl() {
        let config = EncryptionConfig::default();
        let tcl = generate_radiant_encrypt_tcl(&config).unwrap();
        assert!(tcl.contains("Radiant"));
        assert!(tcl.contains("ENCRYPT"));
        assert!(tcl.contains("export_encrypted_hdl"));
    }

    #[test]
    fn test_protect_region() {
        let region = ProtectRegion {
            name: "core_logic".to_string(),
            start_line: 100,
            end_line: 200,
            encryption_key: "secret_key_123".to_string(),
            allow_synthesis: true,
            allow_simulation: false,
            allow_encryption: true,
        };

        assert_eq!(region.name, "core_logic");
        assert!(!region.allow_simulation);
        assert!(region.allow_encryption);
    }

    #[test]
    fn test_encrypted_file_info() {
        let file = EncryptedFile {
            original_path: PathBuf::from("design.v"),
            encrypted_path: PathBuf::from("design_enc.v"),
            wrapper_path: Some(PathBuf::from("design_wrapper.v")),
            standard: EncryptionStandard::IeeeP1735,
            key_checksum: "abc123".to_string(),
        };

        assert_eq!(file.original_path.to_str().unwrap(), "design.v");
        assert!(file.wrapper_path.is_some());
    }
}
