use crate::backend::BackendResult;
use serde::{Deserialize, Serialize};

/// Reveal trigger operator
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum TriggerOperator {
    Equal,
    NotEqual,
    LessThan,
    GreaterThan,
    LessEqual,
    GreaterEqual,
    BitPattern,
}

impl std::fmt::Display for TriggerOperator {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            TriggerOperator::Equal => write!(f, "=="),
            TriggerOperator::NotEqual => write!(f, "!="),
            TriggerOperator::LessThan => write!(f, "<"),
            TriggerOperator::GreaterThan => write!(f, ">"),
            TriggerOperator::LessEqual => write!(f, "<="),
            TriggerOperator::GreaterEqual => write!(f, ">="),
            TriggerOperator::BitPattern => write!(f, "pattern"),
        }
    }
}

/// Reveal trigger mode
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum TriggerMode {
    Always,
    Once,
    Conditional,
    Sequential,
}

impl std::fmt::Display for TriggerMode {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            TriggerMode::Always => write!(f, "always"),
            TriggerMode::Once => write!(f, "once"),
            TriggerMode::Conditional => write!(f, "conditional"),
            TriggerMode::Sequential => write!(f, "sequential"),
        }
    }
}

/// Trigger signal specification
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TriggerSignal {
    pub signal_name: String,
    pub operator: TriggerOperator,
    pub value: String,
}

/// Revealed signal capture
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CapturedSignal {
    pub signal_name: String,
    pub bit_width: u32,
    pub start_position: u32,
    pub end_position: u32,
}

/// Reveal configuration
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RevealConfig {
    pub design_name: String,
    pub capture_depth: u32,
    pub trigger_mode: TriggerMode,
    pub trigger_signals: Vec<TriggerSignal>,
    pub capture_signals: Vec<CapturedSignal>,
    pub enable_analysis: bool,
}

impl Default for RevealConfig {
    fn default() -> Self {
        Self {
            design_name: "top".to_string(),
            capture_depth: 1024,
            trigger_mode: TriggerMode::Always,
            trigger_signals: vec![],
            capture_signals: vec![],
            enable_analysis: false,
        }
    }
}

/// Generate Reveal Inserter TCL script
pub fn generate_reveal_inserter_tcl(config: &RevealConfig) -> BackendResult<String> {
    let mut tcl = String::from(
        r#"# Reveal Inserter Script - Generated by CovertEDA
# Design: "#,
    );
    tcl.push_str(&config.design_name);
    tcl.push_str(
        r#"

# Configure Reveal parameters
open_project [get_project_name]

# Create Reveal instance
set reveal_core [ipgen_create_core reveal_core Reveal2 1.0]

# Configure capture depth
set_param -dict [list \
    CAPTURE_DEPTH "#,
    );
    tcl.push_str(&config.capture_depth.to_string());
    tcl.push_str(
        r#" \
    TRIGGER_MODE "#,
    );
    tcl.push_str(&config.trigger_mode.to_string());
    tcl.push_str(
        r#" \
    ] $reveal_core

# Add capture signals
"#,
    );

    for (idx, signal) in config.capture_signals.iter().enumerate() {
        tcl.push_str(&format!(
            "add_reveal_signal -index {} -signal {{{}}} -width {}\n",
            idx, signal.signal_name, signal.bit_width
        ));
    }

    tcl.push_str(
        r#"

# Add trigger conditions
"#,
    );

    for trigger in &config.trigger_signals {
        tcl.push_str(&format!(
            "set_reveal_trigger -signal {{{}}} -operator {{{}}} -value {}\n",
            trigger.signal_name, trigger.operator, trigger.value
        ));
    }

    tcl.push_str(
        r#"

# Synthesize Reveal core
generate_ip

puts "Reveal Inserter configured successfully"
"#,
    );

    Ok(tcl)
}

/// Generate Reveal Analyzer TCL script
pub fn generate_reveal_analyzer_tcl(config: &RevealConfig) -> BackendResult<String> {
    let mut tcl = String::from(
        r#"# Reveal Analyzer Script - Generated by CovertEDA
# Design: "#,
    );
    tcl.push_str(&config.design_name);
    tcl.push_str(
        r#"

# Open project and device
open_project [get_project_name]

# Create Reveal analyzer instance
set analyzer [reveal_create_analyzer]

# Configure trigger conditions
"#,
    );

    for trigger in &config.trigger_signals {
        tcl.push_str(&format!(
            "reveal_set_trigger -signal {{{}}} -condition {{{}}} \n",
            trigger.signal_name,
            match trigger.operator {
                TriggerOperator::Equal => format!("== {}", trigger.value),
                TriggerOperator::NotEqual => format!("!= {}", trigger.value),
                TriggerOperator::LessThan => format!("< {}", trigger.value),
                TriggerOperator::GreaterThan => format!("> {}", trigger.value),
                TriggerOperator::LessEqual => format!("<= {}", trigger.value),
                TriggerOperator::GreaterEqual => format!(">= {}", trigger.value),
                TriggerOperator::BitPattern => format!("pattern {}", trigger.value),
            }
        ));
    }

    if config.enable_analysis {
        tcl.push_str(
            r#"

# Enable analysis features
reveal_enable_analysis
reveal_configure_statistics

# Export analyzer configuration
reveal_export_config -format json -output reveal_config.json
"#,
        );
    }

    tcl.push_str("\nputs \"Reveal Analyzer configured\"\n");

    Ok(tcl)
}

/// Parse captured waveform data
pub fn parse_reveal_capture(waveform_data: &str) -> BackendResult<Vec<CapturedSignal>> {
    let mut signals = vec![];

    for line in waveform_data.lines() {
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }

        let parts: Vec<&str> = line.split_whitespace().collect();
        if parts.len() >= 3 {
            if let (Ok(width), Ok(start), Ok(end)) = (
                parts[1].parse::<u32>(),
                parts[2].parse::<u32>(),
                parts[3].parse::<u32>(),
            ) {
                signals.push(CapturedSignal {
                    signal_name: parts[0].to_string(),
                    bit_width: width,
                    start_position: start,
                    end_position: end,
                });
            }
        }
    }

    Ok(signals)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_reveal_config_default() {
        let config = RevealConfig::default();
        assert_eq!(config.design_name, "top");
        assert_eq!(config.capture_depth, 1024);
        assert!(!config.enable_analysis);
    }

    #[test]
    fn test_generate_reveal_inserter_tcl() {
        let config = RevealConfig::default();
        let tcl = generate_reveal_inserter_tcl(&config).unwrap();
        assert!(tcl.contains("Reveal Inserter"));
        assert!(tcl.contains("CAPTURE_DEPTH"));
        assert!(tcl.contains("top"));
    }

    #[test]
    fn test_generate_reveal_analyzer_tcl() {
        let mut config = RevealConfig::default();
        config.enable_analysis = true;
        config.trigger_signals.push(TriggerSignal {
            signal_name: "clk".to_string(),
            operator: TriggerOperator::Equal,
            value: "1".to_string(),
        });

        let tcl = generate_reveal_analyzer_tcl(&config).unwrap();
        assert!(tcl.contains("Reveal Analyzer"));
        assert!(tcl.contains("trigger"));
        assert!(tcl.contains("analysis"));
    }

    #[test]
    fn test_trigger_operator_display() {
        assert_eq!(TriggerOperator::Equal.to_string(), "==");
        assert_eq!(TriggerOperator::NotEqual.to_string(), "!=");
        assert_eq!(TriggerOperator::LessThan.to_string(), "<");
    }

    #[test]
    fn test_parse_reveal_capture() {
        let data = "clk 1 0 100\ndata 8 100 200\nvalid 1 200 300";
        let signals = parse_reveal_capture(data).unwrap();
        assert_eq!(signals.len(), 3);
        assert_eq!(signals[0].signal_name, "clk");
        assert_eq!(signals[0].bit_width, 1);
    }
}
