use crate::backend::BackendResult;
use serde::{Deserialize, Serialize};

/// SED (Single Event Upset) Notification options
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum SedNotification {
    None,
    Register,
    Interrupt,
    Gpio,
    Fifo,
}

impl std::fmt::Display for SedNotification {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            SedNotification::None => write!(f, "none"),
            SedNotification::Register => write!(f, "register"),
            SedNotification::Interrupt => write!(f, "interrupt"),
            SedNotification::Gpio => write!(f, "gpio"),
            SedNotification::Fifo => write!(f, "fifo"),
        }
    }
}

/// SEU (Single Event Upset) Mitigation strategy
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub enum SeuMitigation {
    None,
    TMR,          // Triple Module Redundancy
    DuplicateFF,  // Duplicate Flip-Flop
    CRC,          // Cyclic Redundancy Check
    ECMH,         // Enhanced Configuration Memory Hardness
}

impl std::fmt::Display for SeuMitigation {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            SeuMitigation::None => write!(f, "none"),
            SeuMitigation::TMR => write!(f, "tmr"),
            SeuMitigation::DuplicateFF => write!(f, "duplicate_ff"),
            SeuMitigation::CRC => write!(f, "crc"),
            SeuMitigation::ECMH => write!(f, "ecmh"),
        }
    }
}

/// SEI (Soft Error Immunity) configuration
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SeiConfig {
    pub design_name: String,
    pub enable_seu_mitigation: bool,
    pub mitigation_strategy: SeuMitigation,
    pub enable_scrubbing: bool,
    pub scrub_interval_ms: u32,
    pub sed_notification: SedNotification,
    pub enable_voting: bool,
    pub voting_threshold: u8,
    pub enable_crc_check: bool,
}

impl Default for SeiConfig {
    fn default() -> Self {
        Self {
            design_name: "top".to_string(),
            enable_seu_mitigation: true,
            mitigation_strategy: SeuMitigation::TMR,
            enable_scrubbing: true,
            scrub_interval_ms: 100,
            sed_notification: SedNotification::Interrupt,
            enable_voting: true,
            voting_threshold: 2,
            enable_crc_check: true,
        }
    }
}

/// Generate SEI TCL configuration script
pub fn generate_sei_tcl(config: &SeiConfig) -> BackendResult<String> {
    let mut tcl = String::from(
        r#"# Soft Error Immunity (SEI) Configuration - Generated by CovertEDA
# Design: "#,
    );
    tcl.push_str(&config.design_name);
    tcl.push_str(
        r#"

# Open project
open_project [get_project_name]

# Configure SEI parameters
configure_tool -name {{SYNTHESIZE}} -params {{
    SYNPLIFY_OPTIONS:set_option -define SEI_ENABLED
    SYNPLIFY_OPTIONS:set_option -define SEU_MITIGATION="#,
    );
    tcl.push_str(&config.mitigation_strategy.to_string());
    tcl.push_str(
        r#"
}}

"#,
    );

    // Configure scrubbing
    if config.enable_scrubbing {
        tcl.push_str(&format!(
            r#"# Memory scrubbing configuration
set_param -dict [list \
    MEMORY_SCRUB_ENABLED 1 \
    SCRUB_INTERVAL_MS {} \
]

"#,
            config.scrub_interval_ms
        ));
    }

    // Configure voting mechanism
    if config.enable_voting {
        tcl.push_str(&format!(
            r#"# Voting mechanism for TMR
set_param -dict [list \
    VOTING_ENABLED 1 \
    VOTING_THRESHOLD {} \
    SED_NOTIFICATION {} \
]

"#,
            config.voting_threshold, config.sed_notification
        ));
    }

    // Configure CRC check
    if config.enable_crc_check {
        tcl.push_str(
            r#"# CRC configuration checking
set_param -dict [list \
    CRC_CHECK_ENABLED 1 \
    CONFIG_READBACK_INTERVAL 1000 \
]

"#,
        );
    }

    tcl.push_str(
        r#"# Run synthesis with SEI options
if { [catch {
    run_tool -name SYNTHESIZE
} error_msg] } {
    puts "ERROR: Synthesis with SEI failed: $error_msg"
    exit 1
}

# Verify SEI configuration
puts "SEI configuration applied successfully"
puts "  Mitigation Strategy: "#,
    );
    tcl.push_str(&config.mitigation_strategy.to_string());
    tcl.push_str(
        r#"
  Memory Scrubbing: "#,
    );
    tcl.push_str(&(config.enable_scrubbing as i32).to_string());
    tcl.push_str(
        r#"
  CRC Check: "#,
    );
    tcl.push_str(&(config.enable_crc_check as i32).to_string());
    tcl.push_str("\n");

    Ok(tcl)
}

/// Get default SEI configuration for critical designs
pub fn default_sei_config() -> SeiConfig {
    SeiConfig {
        design_name: "top".to_string(),
        enable_seu_mitigation: true,
        mitigation_strategy: SeuMitigation::TMR,
        enable_scrubbing: true,
        scrub_interval_ms: 100,
        sed_notification: SedNotification::Interrupt,
        enable_voting: true,
        voting_threshold: 2,
        enable_crc_check: true,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_sei_config_default() {
        let config = SeiConfig::default();
        assert_eq!(config.design_name, "top");
        assert!(config.enable_seu_mitigation);
        assert!(config.enable_scrubbing);
        assert!(config.enable_voting);
    }

    #[test]
    fn test_seu_mitigation_display() {
        assert_eq!(SeuMitigation::None.to_string(), "none");
        assert_eq!(SeuMitigation::TMR.to_string(), "tmr");
        assert_eq!(SeuMitigation::DuplicateFF.to_string(), "duplicate_ff");
        assert_eq!(SeuMitigation::CRC.to_string(), "crc");
    }

    #[test]
    fn test_sed_notification_display() {
        assert_eq!(SedNotification::None.to_string(), "none");
        assert_eq!(SedNotification::Register.to_string(), "register");
        assert_eq!(SedNotification::Interrupt.to_string(), "interrupt");
        assert_eq!(SedNotification::Gpio.to_string(), "gpio");
    }

    #[test]
    fn test_generate_sei_tcl_basic() {
        let config = SeiConfig::default();
        let tcl = generate_sei_tcl(&config).unwrap();
        assert!(tcl.contains("Soft Error Immunity"));
        assert!(tcl.contains("SYNTHESIZE"));
        assert!(tcl.contains("SEI_ENABLED"));
    }

    #[test]
    fn test_generate_sei_tcl_with_scrubbing() {
        let config = SeiConfig {
            enable_scrubbing: true,
            scrub_interval_ms: 200,
            ..Default::default()
        };
        let tcl = generate_sei_tcl(&config).unwrap();
        assert!(tcl.contains("MEMORY_SCRUB_ENABLED"));
        assert!(tcl.contains("200"));
    }

    #[test]
    fn test_default_sei_config() {
        let config = default_sei_config();
        assert_eq!(config.mitigation_strategy, SeuMitigation::TMR);
        assert!(config.enable_crc_check);
    }

    #[test]
    fn test_sei_config_custom() {
        let config = SeiConfig {
            design_name: "critical_core".to_string(),
            mitigation_strategy: SeuMitigation::DuplicateFF,
            voting_threshold: 1,
            ..Default::default()
        };

        assert_eq!(config.design_name, "critical_core");
        assert_eq!(config.voting_threshold, 1);
    }
}
