use crate::backend::BackendResult;
use serde::{Deserialize, Serialize};
use std::path::PathBuf;

/// Supported simulators
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum Simulator {
    ModelSim,
    VCS,
    Icarus,
    Verilator,
    XSim,
}

impl std::fmt::Display for Simulator {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Simulator::ModelSim => write!(f, "ModelSim"),
            Simulator::VCS => write!(f, "VCS"),
            Simulator::Icarus => write!(f, "Icarus"),
            Simulator::Verilator => write!(f, "Verilator"),
            Simulator::XSim => write!(f, "XSim"),
        }
    }
}

/// Waveform output format
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum WaveformFormat {
    VCD,
    FST,
    EVCD,
    WDB,
}

impl std::fmt::Display for WaveformFormat {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            WaveformFormat::VCD => write!(f, "vcd"),
            WaveformFormat::FST => write!(f, "fst"),
            WaveformFormat::EVCD => write!(f, "evcd"),
            WaveformFormat::WDB => write!(f, "wdb"),
        }
    }
}

/// Simulation configuration
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SimConfig {
    pub simulator: Simulator,
    pub design_name: String,
    pub testbench: String,
    pub output_dir: PathBuf,
    pub waveform_format: WaveformFormat,
    pub simulation_time_ns: u64,
    pub include_paths: Vec<PathBuf>,
    pub source_files: Vec<PathBuf>,
    pub compile_libs: Vec<String>,
}

impl Default for SimConfig {
    fn default() -> Self {
        Self {
            simulator: Simulator::ModelSim,
            design_name: "top".to_string(),
            testbench: "tb_top".to_string(),
            output_dir: PathBuf::from("."),
            waveform_format: WaveformFormat::VCD,
            simulation_time_ns: 1000,
            include_paths: vec![],
            source_files: vec![],
            compile_libs: vec!["work".to_string()],
        }
    }
}

/// Generate simulation project files
pub fn generate_sim_project(config: &SimConfig) -> BackendResult<String> {
    match config.simulator {
        Simulator::ModelSim => generate_modelsim_do(config),
        Simulator::Icarus => generate_icarus_sh(config),
        Simulator::Verilator => generate_verilator_sh(config),
        _ => Err(crate::backend::BackendError::ConfigError(
            "Unsupported simulator".to_string(),
        )),
    }
}

/// Generate ModelSim .do script
fn generate_modelsim_do(config: &SimConfig) -> BackendResult<String> {
    let mut script = String::from(
        r#"# ModelSim Simulation Script - Generated by CovertEDA
# Design: "#,
    );
    script.push_str(&config.design_name);
    script.push_str("\n# Testbench: ");
    script.push_str(&config.testbench);
    script.push_str(
        r#"

# Create work library
vlib work
vmap work ./work

# Compile design files
"#,
    );

    for src_file in &config.source_files {
        script.push_str(&format!("vlog {}\n", src_file.display()));
    }

    script.push_str(&format!(
        r#"

# Elaborate design
vsim -voptargs=+acc work.{}

# Add waveforms
add wave -r /*

# Run simulation
run {} ns

# Save waveform
write_wave -format {}dump wave.{}

# Exit
quit
"#,
        config.testbench,
        config.simulation_time_ns,
        match config.waveform_format {
            WaveformFormat::VCD => "vc",
            WaveformFormat::FST => "fst",
            _ => "vc",
        },
        match config.waveform_format {
            WaveformFormat::VCD => "vcd",
            WaveformFormat::FST => "fst",
            _ => "vcd",
        }
    ));

    Ok(script)
}

/// Generate Icarus Verilog shell script
fn generate_icarus_sh(config: &SimConfig) -> BackendResult<String> {
    let mut script = String::from(
        r#"#!/bin/bash
# Icarus Verilog Simulation Script - Generated by CovertEDA
# Design: "#,
    );
    script.push_str(&config.design_name);
    script.push_str("\n# Testbench: ");
    script.push_str(&config.testbench);
    script.push_str(
        r#"

# Compile sources
iverilog -o simulation.vvp \
"#,
    );

    for src_file in &config.source_files {
        script.push_str(&format!("    {} \\\n", src_file.display()));
    }

    script.push_str(
        r#"
    2>/dev/null || {{ echo "Compilation failed"; exit 1; }}

# Run simulation
vvp -n simulation.vvp -l simulation.log

# Convert waveform
if [ -f dump.vcd ]; then
    echo "Simulation completed. Waveform: dump.vcd"
else
    echo "No waveform generated"
fi
"#,
    );

    Ok(script)
}

/// Generate Verilator shell script
fn generate_verilator_sh(config: &SimConfig) -> BackendResult<String> {
    let mut script = String::from(
        r#"#!/bin/bash
# Verilator Simulation Script - Generated by CovertEDA
# Design: "#,
    );
    script.push_str(&config.design_name);
    script.push_str("\n\n# Configure Verilator\n");
    script.push_str(
        r#"verilator -Wno-fatal --trace \
    --exe --build -j 4 \
    --cc \
"#,
    );

    for src_file in &config.source_files {
        script.push_str(&format!("    {} \\\n", src_file.display()));
    }

    script.push_str(
        r#"
    2>&1 | tee verilator.log

if [ $? -eq 0 ]; then
    echo "Verilator compilation successful"
    ./obj_dir/V"#,
    );
    script.push_str(&config.design_name);
    script.push_str(
        r#"
else
    echo "Verilator compilation failed"
    exit 1
fi
"#,
    );

    Ok(script)
}

/// Find testbenches in source directory
pub fn find_testbenches(src_dir: &std::path::Path) -> BackendResult<Vec<String>> {
    let mut testbenches = vec![];

    if src_dir.exists() {
        for entry in std::fs::read_dir(src_dir)? {
            let entry = entry?;
            let path = entry.path();
            if let Some(ext) = path.extension().and_then(|e| e.to_str()) {
                if ext == "v" || ext == "sv" {
                    let name = path.file_stem().and_then(|n| n.to_str()).unwrap_or("");
                    if name.starts_with("tb_") || name.contains("_tb") {
                        testbenches.push(name.to_string());
                    }
                }
            }
        }
    }

    Ok(testbenches)
}

/// Generate compile_libs.tcl for simulation
pub fn generate_compile_libs_tcl(lib_names: &[&str]) -> BackendResult<String> {
    let mut tcl = String::from("# Compile Libraries Script - Generated by CovertEDA\n\n");

    for lib_name in lib_names {
        tcl.push_str(&format!("vlib {}\n", lib_name));
        tcl.push_str(&format!("vmap {} ./work_{}\n", lib_name, lib_name));
    }

    Ok(tcl)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_sim_config_default() {
        let config = SimConfig::default();
        assert_eq!(config.design_name, "top");
        assert_eq!(config.testbench, "tb_top");
        assert_eq!(config.simulation_time_ns, 1000);
    }

    #[test]
    fn test_generate_modelsim_do() {
        let config = SimConfig::default();
        let script = generate_modelsim_do(&config).unwrap();
        assert!(script.contains("ModelSim"));
        assert!(script.contains("vlib work"));
        assert!(script.contains("vsim"));
        assert!(script.contains("vcd"));
    }

    #[test]
    fn test_generate_icarus_sh() {
        let config = SimConfig::default();
        let script = generate_icarus_sh(&config).unwrap();
        assert!(script.contains("Icarus"));
        assert!(script.contains("iverilog"));
        assert!(script.contains("vvp"));
    }

    #[test]
    fn test_generate_verilator_sh() {
        let config = SimConfig::default();
        let script = generate_verilator_sh(&config).unwrap();
        assert!(script.contains("Verilator"));
        assert!(script.contains("--trace"));
        assert!(script.contains("--build"));
    }

    #[test]
    fn test_simulator_display() {
        assert_eq!(Simulator::ModelSim.to_string(), "ModelSim");
        assert_eq!(Simulator::Icarus.to_string(), "Icarus");
        assert_eq!(Simulator::Verilator.to_string(), "Verilator");
    }

    #[test]
    fn test_generate_compile_libs_tcl() {
        let libs = vec!["work", "xilinx", "unisim"];
        let tcl = generate_compile_libs_tcl(&libs).unwrap();
        assert!(tcl.contains("vlib work"));
        assert!(tcl.contains("vlib xilinx"));
        assert!(tcl.contains("vlib unisim"));
    }
}
