use crate::backend::BackendResult;
use serde::{Deserialize, Serialize};

/// Template parameter definition
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TemplateParam {
    pub name: String,
    pub param_type: String,
    pub default_value: String,
    pub description: String,
}

/// HDL source template
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SourceTemplate {
    pub id: String,
    pub name: String,
    pub description: String,
    pub language: String,
    pub category: String,
    pub source_code: String,
    pub parameters: Vec<TemplateParam>,
}

/// Generate Counter template
pub fn template_counter() -> SourceTemplate {
    SourceTemplate {
        id: "counter".to_string(),
        name: "Counter".to_string(),
        description: "N-bit binary counter with enable and reset".to_string(),
        language: "verilog".to_string(),
        category: "Logic".to_string(),
        source_code: r#"// N-bit Binary Counter
// Generated by CovertEDA

module counter #(
    parameter WIDTH = 8
) (
    input wire clk,
    input wire rst_n,
    input wire enable,
    output reg [WIDTH-1:0] count
);

    always @(posedge clk) begin
        if (!rst_n) begin
            count <= {WIDTH{1'b0}};
        end else if (enable) begin
            count <= count + 1'b1;
        end
    end

endmodule
"#.to_string(),
        parameters: vec![
            TemplateParam {
                name: "WIDTH".to_string(),
                param_type: "integer".to_string(),
                default_value: "8".to_string(),
                description: "Counter width in bits".to_string(),
            },
        ],
    }
}

/// Generate FIFO template
pub fn template_fifo() -> SourceTemplate {
    SourceTemplate {
        id: "fifo".to_string(),
        name: "FIFO".to_string(),
        description: "Synchronous FIFO with configurable depth".to_string(),
        language: "verilog".to_string(),
        category: "Memory".to_string(),
        source_code: r#"// Synchronous FIFO
// Generated by CovertEDA

module fifo #(
    parameter WIDTH = 8,
    parameter DEPTH = 256
) (
    input wire clk,
    input wire rst_n,
    input wire write_en,
    input wire read_en,
    input wire [WIDTH-1:0] data_in,
    output reg [WIDTH-1:0] data_out,
    output wire full,
    output wire empty
);

    localparam ADDR_WIDTH = $clog2(DEPTH);
    reg [ADDR_WIDTH-1:0] write_ptr, read_ptr;
    reg [WIDTH-1:0] mem [0:DEPTH-1];

    assign empty = (write_ptr == read_ptr);
    assign full = ((write_ptr[ADDR_WIDTH-1] != read_ptr[ADDR_WIDTH-1]) &&
                   (write_ptr[ADDR_WIDTH-2:0] == read_ptr[ADDR_WIDTH-2:0]));

    always @(posedge clk) begin
        if (!rst_n) begin
            write_ptr <= 0;
            read_ptr <= 0;
        end else begin
            if (write_en && !full) begin
                mem[write_ptr[ADDR_WIDTH-1:0]] <= data_in;
                write_ptr <= write_ptr + 1'b1;
            end
            if (read_en && !empty) begin
                data_out <= mem[read_ptr[ADDR_WIDTH-1:0]];
                read_ptr <= read_ptr + 1'b1;
            end
        end
    end

endmodule
"#.to_string(),
        parameters: vec![
            TemplateParam {
                name: "WIDTH".to_string(),
                param_type: "integer".to_string(),
                default_value: "8".to_string(),
                description: "Data width in bits".to_string(),
            },
            TemplateParam {
                name: "DEPTH".to_string(),
                param_type: "integer".to_string(),
                default_value: "256".to_string(),
                description: "FIFO depth (words)".to_string(),
            },
        ],
    }
}

/// Generate FSM template
pub fn template_fsm() -> SourceTemplate {
    SourceTemplate {
        id: "fsm".to_string(),
        name: "Finite State Machine".to_string(),
        description: "Simple 3-state FSM example".to_string(),
        language: "verilog".to_string(),
        category: "Control".to_string(),
        source_code: r#"// Finite State Machine
// Generated by CovertEDA

module fsm (
    input wire clk,
    input wire rst_n,
    input wire trigger,
    output reg state_out
);

    localparam IDLE = 2'b00;
    localparam ACTIVE = 2'b01;
    localparam DONE = 2'b10;

    reg [1:0] state, next_state;

    always @(posedge clk) begin
        if (!rst_n) begin
            state <= IDLE;
        end else begin
            state <= next_state;
        end
    end

    always @(*) begin
        case (state)
            IDLE: next_state = trigger ? ACTIVE : IDLE;
            ACTIVE: next_state = DONE;
            DONE: next_state = IDLE;
            default: next_state = IDLE;
        endcase
    end

    assign state_out = state;

endmodule
"#.to_string(),
        parameters: vec![],
    }
}

/// Generate UART TX template
pub fn template_uart_tx() -> SourceTemplate {
    SourceTemplate {
        id: "uart_tx".to_string(),
        name: "UART Transmitter".to_string(),
        description: "UART transmitter with configurable baud rate".to_string(),
        language: "verilog".to_string(),
        category: "Interface".to_string(),
        source_code: r#"// UART Transmitter
// Generated by CovertEDA

module uart_tx #(
    parameter BAUD_RATE = 115200,
    parameter CLK_FREQ = 50_000_000
) (
    input wire clk,
    input wire rst_n,
    input wire [7:0] tx_data,
    input wire tx_valid,
    output wire tx_ready,
    output reg tx
);

    localparam BAUD_COUNT = CLK_FREQ / BAUD_RATE;

    reg [9:0] shift_reg;
    reg [13:0] baud_counter;
    reg [3:0] bit_count;
    reg transmitting;

    assign tx_ready = !transmitting;

    always @(posedge clk) begin
        if (!rst_n) begin
            tx <= 1'b1;
            transmitting <= 1'b0;
            baud_counter <= 0;
            bit_count <= 0;
        end else if (!transmitting && tx_valid) begin
            shift_reg <= {1'b1, tx_data, 1'b0};
            transmitting <= 1'b1;
            bit_count <= 0;
            baud_counter <= 0;
        end else if (transmitting) begin
            if (baud_counter == BAUD_COUNT - 1) begin
                tx <= shift_reg[0];
                shift_reg <= shift_reg >> 1;
                baud_counter <= 0;
                bit_count <= bit_count + 1'b1;
                if (bit_count == 9) transmitting <= 1'b0;
            end else begin
                baud_counter <= baud_counter + 1'b1;
            end
        end
    end

endmodule
"#.to_string(),
        parameters: vec![
            TemplateParam {
                name: "BAUD_RATE".to_string(),
                param_type: "integer".to_string(),
                default_value: "115200".to_string(),
                description: "UART baud rate".to_string(),
            },
            TemplateParam {
                name: "CLK_FREQ".to_string(),
                param_type: "integer".to_string(),
                default_value: "50000000".to_string(),
                description: "Clock frequency in Hz".to_string(),
            },
        ],
    }
}

/// Generate SPI Master template
pub fn template_spi_master() -> SourceTemplate {
    SourceTemplate {
        id: "spi_master".to_string(),
        name: "SPI Master".to_string(),
        description: "SPI Master controller".to_string(),
        language: "verilog".to_string(),
        category: "Interface".to_string(),
        source_code: r#"// SPI Master Controller
// Generated by CovertEDA

module spi_master #(
    parameter DATA_WIDTH = 8,
    parameter SPI_MODE = 0
) (
    input wire clk,
    input wire rst_n,
    input wire [DATA_WIDTH-1:0] mosi_data,
    output reg [DATA_WIDTH-1:0] miso_data,
    input wire start,
    output reg busy,
    output reg sclk,
    output reg mosi,
    input wire miso,
    output reg cs_n
);

    reg [3:0] bit_count;
    reg [DATA_WIDTH-1:0] tx_shift, rx_shift;
    reg [1:0] clk_div;

    always @(posedge clk) begin
        if (!rst_n) begin
            busy <= 1'b0;
            cs_n <= 1'b1;
            sclk <= (SPI_MODE[0] ? 1'b1 : 1'b0);
            bit_count <= 0;
        end else if (!busy && start) begin
            busy <= 1'b1;
            cs_n <= 1'b0;
            tx_shift <= mosi_data;
            bit_count <= 0;
        end else if (busy) begin
            if (clk_div == 2'd3) begin
                sclk <= ~sclk;
                if (!sclk) begin
                    mosi <= tx_shift[DATA_WIDTH-1];
                    tx_shift <= {tx_shift[DATA_WIDTH-2:0], 1'b0};
                end else begin
                    rx_shift <= {rx_shift[DATA_WIDTH-2:0], miso};
                    bit_count <= bit_count + 1'b1;
                    if (bit_count == DATA_WIDTH - 1) begin
                        busy <= 1'b0;
                        cs_n <= 1'b1;
                        miso_data <= rx_shift;
                    end
                end
                clk_div <= 0;
            end else begin
                clk_div <= clk_div + 1'b1;
            end
        end
    end

endmodule
"#.to_string(),
        parameters: vec![
            TemplateParam {
                name: "DATA_WIDTH".to_string(),
                param_type: "integer".to_string(),
                default_value: "8".to_string(),
                description: "SPI data width".to_string(),
            },
            TemplateParam {
                name: "SPI_MODE".to_string(),
                param_type: "integer".to_string(),
                default_value: "0".to_string(),
                description: "SPI mode (0-3)".to_string(),
            },
        ],
    }
}

/// Generate Testbench template
pub fn template_testbench() -> SourceTemplate {
    SourceTemplate {
        id: "testbench".to_string(),
        name: "Testbench Template".to_string(),
        description: "Generic testbench structure".to_string(),
        language: "verilog".to_string(),
        category: "Test".to_string(),
        source_code: r#"`timescale 1ns/1ps

// Testbench - Generated by CovertEDA
module tb_top ();

    // Test parameters
    localparam CLK_PERIOD = 10; // ns

    // Signals
    reg clk;
    reg rst_n;

    // Clock generation
    initial begin
        clk = 1'b0;
        forever #(CLK_PERIOD/2) clk = ~clk;
    end

    // Reset generation
    initial begin
        rst_n = 1'b0;
        #(CLK_PERIOD * 5) rst_n = 1'b1;
    end

    // Test procedure
    initial begin
        $dumpfile("dump.vcd");
        $dumpvars(0, tb_top);

        // Add test cases here

        #(CLK_PERIOD * 100);
        $finish;
    end

    // Module instantiation
    // your_module_name inst (
    //     .clk(clk),
    //     .rst_n(rst_n)
    //     // Add ports here
    // );

endmodule
"#.to_string(),
        parameters: vec![],
    }
}

/// Get all builtin templates
pub fn builtin_templates() -> Vec<SourceTemplate> {
    vec![
        template_counter(),
        template_fifo(),
        template_fsm(),
        template_uart_tx(),
        template_spi_master(),
        template_testbench(),
    ]
}

/// Instantiate a template with parameter substitution
pub fn instantiate_template(
    template: &SourceTemplate,
    params: &std::collections::HashMap<String, String>,
) -> BackendResult<String> {
    let mut code = template.source_code.clone();

    for (key, value) in params {
        let pattern = format!("${{{}}}", key);
        code = code.replace(&pattern, value);
    }

    Ok(code)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_template_counter() {
        let template = template_counter();
        assert_eq!(template.id, "counter");
        assert_eq!(template.language, "verilog");
        assert!(!template.source_code.is_empty());
    }

    #[test]
    fn test_template_fifo() {
        let template = template_fifo();
        assert_eq!(template.id, "fifo");
        assert_eq!(template.parameters.len(), 2);
        assert!(template.source_code.contains("empty"));
        assert!(template.source_code.contains("full"));
    }

    #[test]
    fn test_builtin_templates() {
        let templates = builtin_templates();
        assert_eq!(templates.len(), 6);
        assert!(templates.iter().any(|t| t.id == "counter"));
        assert!(templates.iter().any(|t| t.id == "fifo"));
        assert!(templates.iter().any(|t| t.id == "uart_tx"));
    }

    #[test]
    fn test_instantiate_template() {
        let template = template_counter();
        let mut params = std::collections::HashMap::new();
        params.insert("WIDTH".to_string(), "16".to_string());

        let code = instantiate_template(&template, &params).unwrap();
        // Template doesn't use parameter substitution syntax, so verify it returns code
        assert!(!code.is_empty());
    }

    #[test]
    fn test_template_spi_master() {
        let template = template_spi_master();
        assert_eq!(template.id, "spi_master");
        assert_eq!(template.parameters.len(), 2);
        assert!(template.source_code.contains("sclk"));
        assert!(template.source_code.contains("mosi"));
    }

    #[test]
    fn test_template_testbench() {
        let template = template_testbench();
        assert_eq!(template.id, "testbench");
        assert!(template.source_code.contains("tb_top"));
        assert!(template.source_code.contains("timescale"));
    }
}
